# Generated by Django 4.2.2 on 2025-08-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Записи пользователя",
                    ),
                ),
                (
                    "subject_note",
                    models.CharField(
                        blank=True,
                        help_text="Введите тему",
                        max_length=100,
                        null=True,
                        verbose_name="Тема запись",
                    ),
                ),
                (
                    "text_note",
                    models.TextField(
                        blank=True,
                        help_text="Введите текст",
                        max_length=300,
                        null=True,
                        verbose_name="Текст записи",
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["text_note"],
                "permissions": [
                    ("can_edit_subject_note", "Can edit subject_note"),
                    ("can_edit_text_note", "Can edit text_note"),
                ],
            },
        ),
    ]
