# Generated by Django 4.2.2 on 2025-08-27 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dear_diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора записи",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
