# Generated by Django 4.2.2 on 2025-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dear_diary", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="public",
            field=models.BooleanField(
                default=False, verbose_name="Признак публичности записи"
            ),
        ),
    ]
