# Generated by Django 4.2.2 on 2025-08-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dear_diary", "0004_alter_note_text_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="text_note",
            field=models.TextField(
                blank=True,
                help_text="Введите текст",
                max_length=10000,
                null=True,
                verbose_name="Текст записи",
            ),
        ),
    ]
