# Generated by Django 4.2.2 on 2025-09-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dear_diary", "0005_alter_note_text_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="date_publication",
            field=models.DateField(
                auto_now=True, verbose_name="Дата публикации записи"
            ),
        ),
    ]
