# Generated by Django 4.2.2 on 2025-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dear_diary", "0006_note_date_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="photos",
                verbose_name="Аватар",
            ),
        ),
    ]
