# Generated by Django 4.2.2 on 2025-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dear_diary", "0007_note_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="date_publication",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата публикации записи"
            ),
        ),
    ]
