# Generated by Django 4.2.2 on 2025-09-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dear_diary", "0008_alter_note_date_publication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["subject_note", "text_note"],
                "permissions": [
                    ("can_edit_subject_note", "Can edit subject_note"),
                    ("can_edit_text_note", "Can edit text_note"),
                ],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
